### ISSUE TITLE
Feature Request: ETA

### ISSUE THREAD

**Issue by shadowx360** [lordmulder/MParallel#3]
First, I want to thank you for having such a simple to use replacement for GNU Parallel on Windows. I hacked together a PowerShell script a couple years ago and that was my replacement until Windows Subsystem for Linux. This is much lower overhead than running WSL.

I want to submit a feature request to display estimated time remaining at top of title bar, updated when a task finishes. GNU Parallel has that feature that displays at the bottom of the console window but I since the title is already being updated with progress, it makes sense to put it into the title for MParallel.

**Comment by lordmulder** [comment]
Hello,

I think the problem is that computing "ETA" is very difficult. Yes, we already show the "progress" in the title bar, but this is simply the number of tasks completed so far divided by the total number of tasks. 

MParallel can easily determine that amount of time that has elapsed so far. But it has **no** clue how long an individual task is going to take. It can **not** even determine the progress of a certain *running* task.

If, and only if, ***all*** tasks in the queue take about the same time to complete – which generally is **not** the case at all – *and* there is a **huge** number of tasks (so that the running time of a *single* tasks is negligible compared to the *total* running time), then we may be able to compute a useful "ETA". But that's a big **IF**!

Also, the fact that we are *not* running the queued tasks sequentially, but instead we'll usually be running **N** tasks in parallel, doesn't really simplify the computation 😁 

So I'm **not** convinced "ETA" computation is that useful in practice (for most scenarios). Sorry about that!

Regards
MuldeR

-----

BTW: I have **no** clue how and what "GNU Parallel" is doing 😕
