### ISSUE TITLE
line break in pattern?

### ISSUE THREAD

**Issue by pixelblender** [lordmulder/MParallel#4]
Usually windows batch takes ^ character as line break just like unix \\. Say if I pass cmake with long flags as pattern, How do I put line break within the --pattern?

Thanks for this awesome tool!

**Comment by lordmulder** [comment]
Hello.

I don't think you can have a "line break" in your *command-**line***, in the sense of a *line-feed* (`0x0A`) or *carriage-return* (`0x0D`) character. Yes, in Batch files you can put a **`^`** symbol at the end of the line, which tells the Batch interpreter "_command continues in next line"_. But this does **not** put a "line break" in the command-line! It rather *concatenates* several lines from your Batch file to a ***single*** command-line. This happens in Batch interpreter. And *then* the command-line, as a whole, will be passed to the program.

You can easily verify this with the following [*test program*](https://gist.github.com/lordmulder/3227e97e99bf5da0c08e9ebf9e79cf36) I have attached:
[**args.2018-12-26.zip**](https://github.com/lordmulder/MParallel/files/2710513/args.2018-12-26.zip)

Above program does nothing but print *all* command-lin arguments, as they arrive at `main()` function.

Regards
MuldeR

**Comment by pixelblender** [comment]
Yes, exactly. Is it possible to have that kind of flexibility to concatenate multiple lines within the enclosed quote of --pattern ?

**Comment by lordmulder** [comment]
Hello.

Again, this is **not** about MParallel, but all about how Windows' Batch interpreter (`cmd.exe`) assembles multiple lines to a single command, when you put a **`^`** char at the end of a line in a Batch file.

It appears that, ***within*** a *quoted string*, Batch does **not** allow you to put a **`^`** char in order to make the command continue on next line! Or, in other words, you apparently can **not** make a single *quoted string* continue in the next line. You can easily confirm this behavior with **args** tool from my previous post:
```
args.exe "aaaa^
bbbb"
```
This does **not** work 😠

You would expect that the the single argument string `aaaabbbb` is sent to **args.exe**. But, in fact, the argument string `aaaa^` is passed to **args.exe**, whereas `bbbb` is executed as a *separate* command!

```
Args [Dec 26 2018]

argv[0] = "args.exe"
argv[1] = "aaaa^"

'bbbb"' is not recognized as an internal or external command,
operable program or batch file.
```

---------------

So, obviously, all that you can do is this:

```
args.exe "aaaa" ^
"bbbb"
```

But then, of course, you will have two ***separate*** argument strings (command-line options):

```
Args [Dec 26 2018]

argv[0] = "args.exe"
argv[1] = "aaaa"
argv[2] = "bbbb"
```

---------------

Then again, I have **no** clue why you would need the pattern string to span *multiple* lines ❓ 

You could always do something like this with Batch syntax:
```
set "MY_PATTERN=aaaa"
set "MY_PATTERN=%MY_PATTERN% bbbb"
set "MY_PATTERN=%MY_PATTERN% cccc"

MParallel.exe --pattern="%MY_PATTERN%" [...]
```

...which, of course, is equivalent to:

```
MParallel.exe --pattern="aaaa bbbb cccc" [...]
```

Regards
MuldeR
